//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiEnCasa_v01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuestos
    {
        public int Id_Presupuesto { get; set; }
        public string Estado { get; set; }
        public System.DateTime Fecha_Vencimiento { get; set; }
        public decimal Precio { get; set; }
        public string Observacion { get; set; }
        public int Solicitudes_Id_Ssolisitud { get; set; }
    
        public virtual Solicitudes Solicitudes { get; set; }
        public virtual Servis Servis { get; set; }
    }
}
